import type { Metadata } from "next";

const SITE_NAME = "NammaAPI";

/**
 * Absolute origin used for canonical URLs, Open Graph URLs, the sitemap and robots.txt.
 * Set NEXT_PUBLIC_SITE_URL (e.g. "https://www.nammaapi.com") in every deployed environment;
 * on Vercel the production domain is used automatically when it isn't set.
 */
function resolveSiteUrl(): string {
  const explicit = process.env.NEXT_PUBLIC_SITE_URL;
  if (explicit) return explicit.replace(/\/+$/, "");

  const vercelProductionHost = process.env.VERCEL_PROJECT_PRODUCTION_URL;
  if (vercelProductionHost) return `https://${vercelProductionHost}`;

  if (process.env.NODE_ENV === "production") {
    console.warn("NEXT_PUBLIC_SITE_URL is not set — canonical URLs and the sitemap will point to localhost.");
  }
  return "http://localhost:3000";
}

const SITE_URL = resolveSiteUrl();

// Generated by app/opengraph-image.tsx. Child segments that set `openGraph` replace the parent's
// object entirely (metadata merges shallowly), so every page has to reference the image itself.
const SHARE_IMAGE = {
  url: "/opengraph-image",
  width: 1200,
  height: 630,
  alt: "NammaAPI — Payment infrastructure and APIs for modern businesses",
};

export function buildMetadata({
  title,
  description,
  path = "",
  noIndex = false,
}: {
  title: string;
  description: string;
  path?: string;
  /** Keep the page out of search results (e.g. login and signup). */
  noIndex?: boolean;
}): Metadata {
  const url = `${SITE_URL}${path}`;
  const fullTitle = `${title} | ${SITE_NAME}`;
  return {
    title: { absolute: fullTitle },
    description,
    alternates: { canonical: url },
    openGraph: {
      title: fullTitle,
      description,
      url,
      siteName: SITE_NAME,
      locale: "en_IN",
      type: "website",
      images: [SHARE_IMAGE],
    },
    twitter: {
      card: "summary_large_image",
      title: fullTitle,
      description,
      images: [SHARE_IMAGE],
    },
    ...(noIndex && { robots: { index: false, follow: true } }),
  };
}

export { SITE_NAME, SITE_URL };
